- name: dotnet publish
        # Note the change to -o . (current directory)
        run: dotnet publish MyModernApi_New/MyModernApi.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mydotnet11'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Point exactly to that publish folder
          package: ./publish