name: Build and Deploy .NET to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x' # Change to 9.x if needed

      - name: Build with dotnet
        run: dotnet build MyModernApi_New/MyModernApi.csproj --configuration Release
        
      - name: dotnet publish
        run: dotnet publish MyModernApi_New/MyModernApi.csproj -c Release -o ./publish

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mydotnet11'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
          # This removes old files that might be causing the 403/Crash
          clean: true 

      - name: 'Force Restart Web App'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp start --name mydotnet11 --resource-group rg-my-project-prod